### ISSUE TITLE
Type error on Safari

### ISSUE THREAD

**Issue by mrhanlon** [asherpasha/AIP_interactions_viewer#4]
@vivekkrish reported to me that he was getting a type error in Safari. It looks like it was happening in the cytoscape.js library. I updated from ~2.2.13 to ^2.3.9 and the error appears fixed now. There was a new option in 2.3.x that adds a "motionBlur", which I have disabled.

I also added bounds on the zooming and turned the zoom sensitivity down.

**Comment by asherpasha** [comment]
Thank you. I will also be updating the README.md file soon.
